module.exports = usersDummy = [
  {
    firstName: 'Yevette',
    lastName: 'Bernot',
    username: 'ybernot0',
    imageURL: 'http://dummyimage.com/206x164.jpg/dddddd/000000',
    email: 'ybernot0@domainmarket.com',
    gender: 'Female',
  },
  {
    firstName: 'Felicdad',
    lastName: 'Punter',
    username: 'fpunter1',
    imageURL: 'http://dummyimage.com/169x157.jpg/dddddd/000000',
    email: 'fpunter1@domainmarket.com',
    gender: 'Female',
  },
  {
    firstName: 'Brigid',
    lastName: 'Mingay',
    username: 'bmingay2',
    imageURL: 'http://dummyimage.com/155x122.jpg/ff4444/ffffff',
    email: 'bmingay2@jigsy.com',
    gender: 'Female',
  },
  {
    firstName: 'Oriana',
    lastName: 'Clubley',
    username: 'oclubley3',
    imageURL: 'http://dummyimage.com/109x128.jpg/ff4444/ffffff',
    email: 'oclubley3@naver.com',
    gender: 'Female',
  },
  {
    firstName: 'Hinda',
    lastName: 'Gason',
    username: 'hgason4',
    imageURL: 'http://dummyimage.com/176x126.jpg/cc0000/ffffff',
    email: 'hgason4@parallels.com',
    gender: 'Female',
  },
  {
    firstName: 'Theodoric',
    lastName: 'Raubenheimer',
    username: 'traubenheimer5',
    imageURL: 'http://dummyimage.com/185x104.jpg/dddddd/000000',
    email: 'traubenheimer5@wiley.com',
    gender: 'Male',
  },
  {
    firstName: 'Consalve',
    lastName: 'Burtwistle',
    username: 'cburtwistle6',
    imageURL: 'http://dummyimage.com/123x167.jpg/5fa2dd/ffffff',
    email: 'cburtwistle6@washington.edu',
    gender: 'Male',
  },
  {
    firstName: 'Teddy',
    lastName: 'Benard',
    username: 'tbenard7',
    imageURL: 'http://dummyimage.com/229x102.jpg/dddddd/000000',
    email: 'tbenard7@naver.com',
    gender: 'Female',
  },
  {
    firstName: 'Delinda',
    lastName: 'Wharmby',
    username: 'dwharmby8',
    imageURL: 'http://dummyimage.com/154x101.jpg/ff4444/ffffff',
    email: 'dwharmby8@va.gov',
    gender: 'Female',
  },
  {
    firstName: 'Melinde',
    lastName: 'Poker',
    username: 'mpoker9',
    imageURL: 'http://dummyimage.com/161x250.jpg/5fa2dd/ffffff',
    email: 'mpoker9@barnesandnoble.com',
    gender: 'Female',
  },
]
